### ISSUE TITLE
Every Compat mod incompatibility

### ISSUE THREAD

**Issue by 1SOH** [M0nkeyPr0grammer/Landscapes-Reimagined-Genesis#10]
When I try to add the "every compat" mod, to make the "Regions Unexplored" materials compatible with "Macaw's Roofs", it just breaks "EMI". Is there a reason for this is will I need to get around this? Thank you!

**Comment by M0nkeyPr0grammer** [comment]
I'd recommend submitting an issue report with Every Compat, as this seems to be an issue directly with them and EMI instead of it being a Landscapes Reimagined Genesis issue.

**Comment by 1SOH** [comment]
I'll do that now, thank you so much!

**Comment by M0nkeyPr0grammer** [comment]
You're welcome, I will keep this issue up until you get a response from them.
