### ISSUE TITLE
Mod Suggestion: SkinShuffle

### ISSUE THREAD

**Issue by IMB11** [M0nkeyPr0grammer/Landscapes-Reimagined-Genesis#11]
https://modrinth.com/mod/skinshuffle

![image-31.png](https://github.com/M0nkeyPr0grammer/Landscapes-Reimagined-Genesis/assets/93472213/79f97b58-7eb3-4f1b-9018-a25185b55f40)

![bef30a864813602bf89d08fe6d103384c867a219.png](https://github.com/M0nkeyPr0grammer/Landscapes-Reimagined-Genesis/assets/93472213/249267f5-d000-4e09-81de-673a5deb7d12)

![e13b4fcd7b37d02aa043e422d2e9560d6f099527.png](https://github.com/M0nkeyPr0grammer/Landscapes-Reimagined-Genesis/assets/93472213/c9b84d9c-871f-41df-abe3-bde6a132f60b)

![0b5e81688937e2685b2fa00ec709c5c1db302648.png](https://github.com/M0nkeyPr0grammer/Landscapes-Reimagined-Genesis/assets/93472213/1408cf00-145a-4911-8ff2-149ac24765d0)

![image-23.png](https://github.com/M0nkeyPr0grammer/Landscapes-Reimagined-Genesis/assets/93472213/deab10fd-b90a-41f8-8c02-48b244174408)

![image-25.png](https://github.com/M0nkeyPr0grammer/Landscapes-Reimagined-Genesis/assets/93472213/68c72aa7-6bfd-429a-81bb-abb33d5d19b0)

![d1f435ad282114885fd9b589c538c8e7250b39ac.png](https://github.com/M0nkeyPr0grammer/Landscapes-Reimagined-Genesis/assets/93472213/9f8c6098-8ad4-49fa-bf75-40f343e5c5bf)

Features:

- Auto Reconnect if the server doesn't have a SkinShuffle compatible plugin or SkinShuffle itself installed.
- Creating skin presets from usernames, UUIDs, URLs, files and built-in skins via resource packs.
- Easy to use interface with clear instructions for non-hotreloadable servers.
- Hot Reload if SkinShuffle or SkinShuffle-compatible plugin is installed on server.
- Hot Reload on LAN (if you're host, or if host has skinshuffle) + Singleplayer worlds.
- Carousel and Compact Grid Layout modes (for smaller and larger screens, or larger and smaller collections of skins!)
- High configurability, can hide skin change widget from title screen/pause screen (can still get to preset change screen via mod menu), can modify the way skins are rendered (follow cursor or rotate on the spot!)

**Comment by M0nkeyPr0grammer** [comment]
Updates for Genesis is currently paused, but once updates resume I can definitely look into that mod to see if it runs without issues in the pack before determining if it will be added.

**Comment by IMB11** [comment]
:+1:
