### ISSUE TITLE
Some client only mods are marked as required on the server

### ISSUE THREAD

**Issue by JulianVennen** [M0nkeyPr0grammer/Landscapes-Reimagined-Genesis#16]
It appears that the following client only mods are marked as required on the server:
- Fancy menu
- Drippy Loading Screen

**Comment by M0nkeyPr0grammer** [comment]
That is an issue on the mod end.

**Comment by JulianVennen** [comment]
The issue is the following:
Fancy menu depends on Melody. Fancy menu is required on both the server and client (in your mrpack), Melody is required only on the client (in your mrpack).
This causes a server created in accordance with the mrpack spec to crash because fancymenu can't find melody.

Either include both of them (they don't appear to cause crashes if they are installed) or exclude both of them on the server

**Comment by M0nkeyPr0grammer** [comment]
As I stated before, this is an issue on the mod end, those client and server side requirements are specified with the mods.toml file internally with each mod's .jar file, which is outside of our control.

**Comment by JulianVennen** [comment]
The fabric.mod.json does not support specifying dependencies for only the client and the dependencies are labelled correctly.

It is inside your control which mods you include on the server so either include both fancy menu and melody or neither of them.
